### ISSUE TITLE
Receiving a fair amount of unsuccessful requests

### ISSUE THREAD

**Issue by CMarshall92** [shinshin86/imgur-anonymous-uploader#1]
not sure why but overall I seem to only be able to upload nine or so images in a promise.all and then it starts to get flaky and return 400 messages from Imgur, any ideas?

![image](https://user-images.githubusercontent.com/33270926/89750795-5f452180-dac5-11ea-8c3d-162df1230f1d.png)

![image](https://user-images.githubusercontent.com/33270926/89750832-7d128680-dac5-11ea-9f14-5b630eacd26c.png)

**Comment by shinshin86** [comment]
@CMarshall92 Thanks for the issue!
I didn't notice the GitHub notification and was late replying to it.

Oh, I see.
This error message is returned when invalid file is received by "Imgur".

Is it possible that you are uploading an image file (png, jpge, jpg) that is not a real image?
For example, if the uploaded image file is different from the entity, it may return 400.

I was able to reproduce the same error by uploading a text file with the "jpg" extension.

I thought it would be better to add a process to determine if a file is valid before it is uploaded, so that the cause of the error can be determined.

I will manage that in a separate issue.

**Comment by shinshin86** [comment]
@CMarshall92 Today I found the "imgur" help page on uploading.
[What files can I upload? What is the size limit? - imgur help](https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-What-is-the-size-limit-)

If your uploaded image files are valid, maybe you have exceeded the maximum size of the file.
Also, there seems to be an upload limit of 50 images per hour.

**Comment by shinshin86** [comment]
This issue has not been updated for a long time and will be closed.
If you have any more problems, please reopen the issue.
Thank you.
